import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { AppThunk, RootState } from '../../config';
import { NewsRepositoryImpl } from '../../data';
import { News, NewsUsecase, Rss, RssPack } from '../../domain';

export interface NewsValue {
  [key: string]: News;
}

export interface NewsPayload {
  key: string;
  data: News;
}

export interface NewsState {
  rssPack: RssPack | null;
  done: boolean;
  selected: string;
  value: NewsValue;
}

const initialState: NewsState = {
  rssPack: null,
  done: true,
  selected: '',
  value: {},
};

export const newsSlice = createSlice({
  name: 'news',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    getRssTodo: state => {
      state.done = false;
    },
    getRssFail: (state, action: PayloadAction<Error>) => {
      if (action.payload.message) {
        alert(action.payload.message);
      }
      state.done = true;
    },
    getRssDone: (state, action: PayloadAction<RssPack>) => {
      state.rssPack = action.payload;
      state.done = true;
    },
    getNewsTodo: (state, action: PayloadAction<string>) => {
      state.selected = action.payload;
      state.done = false;
    },
    getNewsFail: (state, action: PayloadAction<Error>) => {
      if (action.payload.message) {
        alert(action.payload.message);
      }
      state.done = true;
    },
    getNewsDone: (state, action: PayloadAction<NewsPayload>) => {
      if (action.payload && action.payload.key && action.payload.data) {
        state.value[action.payload.key] = action.payload.data;
      }
      state.done = true;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
    console.log('builder: ', builder);
  },
});

export const {
  getRssTodo,
  getRssFail,
  getRssDone,
  getNewsTodo,
  getNewsFail,
  getNewsDone,
} = newsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state.
export const selectRssPack = (state: RootState) => state.news.rssPack;
export const selectNewsValue = (state: RootState) => state.news.value;
export const selectNewsDone = (state: RootState) => state.news.done;
export const selectNewsSelected = (state: RootState) => state.news.selected;

// We can also write thunks by hand, which may contain both sync and async logic.
/**
 * async action
 */
const repo = new NewsRepositoryImpl();
const service = new NewsUsecase(repo);

export const fetchRssPack = (): AppThunk => async dispatch => {
  try {
    dispatch(getRssTodo());
    const rssPack = await service.getRssEditorChoice();
    console.log('thunk - fetchRssPack: ', rssPack);
    dispatch(getRssDone(rssPack));
  } catch (err) {
    console.error('thunk - fetchRssPack: ', err);
    dispatch(getRssFail(err));
  }
};

export const fetchNews =
  (rss: Rss): AppThunk =>
  async dispatch => {
    try {
      console.log(`selected :`, rss.link);
      dispatch(getNewsTodo(rss.link));
      const news = await service.getNews(rss.link);
      console.log('thunk - fetchNews: ', news);
      dispatch(getNewsDone({ key: rss.link, data: news }));
    } catch (err) {
      console.error('thunk - fetchNews: ', err);
      dispatch(getNewsFail(err));
    }
  };

export default newsSlice.reducer;
